models:
    openllama:
        model_name: OpenLLAMAModel
        agent_name: DeepSpeedAgent
        stage1_train_dataset: MVTecDataset
        test_dataset: SelfInstructTestDataset
    openllama_peft:
        model_name: OpenLLAMAPEFTModel
        agent_name: DeepSpeedAgent
        stage1_train_dataset: MVTecDataset
        test_dataset: SelfInstructTestDataset

# ========= Global configuration ========== #
logging_step: 5
# ========= Global configuration ========== #
